-- Generated by CSharp.lua Compiler
local System = System
local VoidSharpORMAttributes
local VoidSharpORMQueryTypes
System.import(function (out)
  VoidSharpORMAttributes = VoidSharp.ORM.Attributes
  VoidSharpORMQueryTypes = VoidSharp.ORM.QueryTypes
end)
System.namespace("VoidSharp.ORM.QueryTypes", function (namespace)
  namespace.class("DropQueryType_1", function (namespace)
    return function (T)
      local GenerateQuery, Execute, __ctor__
      __ctor__ = function (this, database)
        VoidSharpORMQueryTypes.QueryType.__ctor__(this, database)
      end
      GenerateQuery = function (this, type)
        local tableName = VoidSharpORMAttributes.TableAttribute.GetAttributeTable(type)
        return "DROP TABLE " .. tableName .. ";"
      end
      Execute = function (this)
        return System.async(function (async, this)
          local query = this:GenerateQuery(System.typeof(T))
          async:await(this.Database:Query(query, T))
        end, nil, this)
      end
      return {
        base = function (out)
          return {
            out.VoidSharp.ORM.QueryTypes.QueryType
          }
        end,
        GenerateQuery = GenerateQuery,
        Execute = Execute,
        __ctor__ = __ctor__,
        __metadata__ = function (out)
          return {
            methods = {
              { ".ctor", 0x106, nil, out.VoidSharp.ORM.Database },
              { "Execute", 0x86, Execute, System.Task },
              { "GenerateQuery", 0x186, GenerateQuery, System.Type, System.String }
            },
            class = { 0x106, T }
          }
        end
      }
    end
  end)
end)
