-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
System.namespace("VoidSharp.ORM.Attributes", function (namespace)
  namespace.class("AutoIncrementAttribute", function (namespace)
    local IsAutoIncrement, class
    -- <summary>
    -- Does the property have an autoincrement attribute?
    -- </summary>
    -- <param name="classType">A property.</param>
    -- <returns></returns>
    IsAutoIncrement = function (classType)
      local attributes = Linq.ToList(Linq.Where(classType:GetCustomAttributes(false), function (x)
        return x:GetType() == System.typeof(class)
      end))

      local default
      if #attributes > 0 then
        default = System.cast(class, attributes:get(0))
      else
        default = nil
      end
      local attribute = default
      return attribute ~= nil
    end
    class = {
      base = function (out)
        return {
          System.Attribute
        }
      end,
      IsAutoIncrement = IsAutoIncrement,
      __metadata__ = function (out)
        return {
          methods = {
            { "IsAutoIncrement", 0x18E, IsAutoIncrement, System.Reflection.PropertyInfo, System.Boolean }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
