-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
System.namespace("VoidSharp.ORM.Attributes", function (namespace)
  namespace.class("ColumnLengthAttribute", function (namespace)
    local GetAttributeColumnLength, class, __ctor__
    __ctor__ = function (this, columnLength)
      System.Attribute.__ctor__(this)
      this._columnLength = columnLength
    end
    -- <summary>
    -- Gets the length of the column attribute.
    -- </summary>
    -- <param name="classType">A property.</param>
    -- <returns>A nullable int (null if does not have attribute)</returns>
    GetAttributeColumnLength = function (classType)
      local attributes = Linq.ToList(Linq.Where(classType:GetCustomAttributes(false), function (x)
        return x:GetType() == System.typeof(class)
      end))

      local default
      if #attributes > 0 then
        default = System.cast(class, attributes:get(0))
      else
        default = nil
      end
      local attribute = default
      local extern = attribute
      if extern ~= nil then
        extern = extern._columnLength
      end
      return extern
    end
    class = {
      base = function (out)
        return {
          System.Attribute
        }
      end,
      _columnLength = 0,
      GetAttributeColumnLength = GetAttributeColumnLength,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "_columnLength", 0x1, System.Int32 }
          },
          methods = {
            { ".ctor", 0x106, nil, System.Int32 },
            { "GetAttributeColumnLength", 0x18E, GetAttributeColumnLength, System.Reflection.PropertyInfo, System.Nullable(System.Int32) }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
