-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM.Attributes", function (namespace)
  namespace.class("TableAttribute", function (namespace)
    local GetAttributeTable, class, __ctor__
    __ctor__ = function (this, tableName)
      System.Attribute.__ctor__(this)
      this._tableName = tableName
    end
    -- <summary>
    -- Gets the table name of the table attribute.
    -- </summary>
    -- <param name="classType">A property.</param>
    -- <returns>The name of the table (if null, then <c>"voidaccessories_" + classType.Name.ToLower()</c>)</returns>
    GetAttributeTable = function (classType)
      local tableName
      local attributes = System.Attribute.GetCustomAttributes(classType, System.typeof(class))

      local default
      if #attributes > 0 then
        default = System.cast(class, attributes:get(0))
      else
        default = nil
      end
      local attribute = default

      if attribute == nil then
        tableName = "voidaccessories_" .. classType:getName():ToLower()
      else
        tableName = attribute._tableName
      end

      return tableName
    end
    class = {
      base = function (out)
        return {
          System.Attribute
        }
      end,
      GetAttributeTable = GetAttributeTable,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "_tableName", 0x1, System.String }
          },
          methods = {
            { ".ctor", 0x106, nil, System.String },
            { "GetAttributeTable", 0x18E, GetAttributeTable, System.Type, System.String }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
