-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM.Specifiers", function (namespace)
  namespace.class("AlterSpecifier", function (namespace)
    local getName, getDataType, __ctor__
    __ctor__ = function (this, a, b)
      local insertTuple = System.Tuple(a, b)
      this.Alter = insertTuple
    end
    getName = function (this)
      return this.Alter[1]
    end
    getDataType = function (this)
      return this.Alter[2]
    end
    return {
      getName = getName,
      getDataType = getDataType,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Alter", 0x1, System.Tuple },
            { "DataType", 0x206, System.Object, getDataType },
            { "Name", 0x206, System.String, getName }
          },
          methods = {
            { ".ctor", 0x206, nil, System.String, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
