-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM.Specifiers", function (namespace)
  namespace.class("InsertSpecifier", function (namespace)
    local getKey, getValue, __ctor__
    __ctor__ = function (this, a, b)
      local insertTuple = System.Tuple(a, b)
      this.Insert = insertTuple
    end
    getKey = function (this)
      return this.Insert[1]
    end
    getValue = function (this)
      return this.Insert[2]
    end
    return {
      getKey = getKey,
      getValue = getValue,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Insert", 0x1, System.Tuple },
            { "Key", 0x206, System.String, getKey },
            { "Value", 0x206, System.Object, getValue }
          },
          methods = {
            { ".ctor", 0x206, nil, System.String, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
