-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM.Specifiers", function (namespace)
  namespace.class("WhereSpecifier", function (namespace)
    local getKey, getComparator, getValue, __ctor__
    __ctor__ = function (this, a, comparator, b)
      local whereTuple = System.Tuple(a, comparator, b)
      this.Where = whereTuple
    end
    getKey = function (this)
      return this.Where[1]
    end
    getComparator = function (this)
      return this.Where[2]
    end
    getValue = function (this)
      return this.Where[3]
    end
    return {
      getKey = getKey,
      getComparator = getComparator,
      getValue = getValue,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Comparator", 0x206, System.String, getComparator },
            { "Key", 0x206, System.String, getKey },
            { "Value", 0x206, System.Object, getValue },
            { "Where", 0x1, System.Tuple }
          },
          methods = {
            { ".ctor", 0x306, nil, System.String, System.String, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
