//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("YANG Huan")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright ©  YANG Huan 2017")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("The C# to Lua compiler")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.1.0")]
[assembly: System.Reflection.AssemblyProductAttribute("CSharp.lua")]
[assembly: System.Reflection.AssemblyTitleAttribute("CSharp.lua")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.1.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

