-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM", function (namespace)
  -- <summary>
  -- Maps an object to a database and vice-versa.
  -- </summary>
  -- <typeparam name="T"></typeparam>
  namespace.class("DatabaseMapper_1", function (namespace)
    return function (T)
      local __ctor__
      __ctor__ = function (this, database)
        this.Database = database
      end
      return {
        __ctor__ = __ctor__,
        __metadata__ = function (out)
          return {
            properties = {
              { "Database", 0x1, out.VoidSharp.ORM.Database }
            },
            methods = {
              { ".ctor", 0x106, nil, out.VoidSharp.ORM.Database }
            },
            class = { 0x106, T }
          }
        end
      }
    end
  end)
end)
