-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM", function (namespace)
  -- ReSharper disable once ClassNeverInstantiated.Global
  namespace.class("DatabaseConnectionResult", function (namespace)
    local __ctor__
    __ctor__ = function (this, hasFailed, error)
      this.HasFailed = hasFailed
      this.Error = error
    end
    return {
      HasFailed = false,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Error", 0x6, System.String },
            { "HasFailed", 0x6, System.Boolean }
          },
          methods = {
            { ".ctor", 0x206, nil, System.Boolean, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
