-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM", function (namespace)
  namespace.interface("ISerializerBase", function ()
    return {
      __metadata__ = function (out)
        return {
          class = { 0x6 }
        }
      end
    }
  end)
end)
