-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM.Migrations", function (namespace)
  namespace.class("Migration", function (namespace)
    return {
      __metadata__ = function (out)
        return {
          class = { 0x6 }
        }
      end
    }
  end)
end)
