-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.Networking", function (namespace)
  namespace.interface("INetworkSerializer", function ()
    return {
      __metadata__ = function (out)
        return {
          class = { 0x6 }
        }
      end
    }
  end)
end)
