-- Generated by CSharp.lua Compiler
local System = System
local VoidSharpNetworking
local DictTypeINetworkSerializer
System.import(function (out)
  VoidSharpNetworking = VoidSharp.Networking
  DictTypeINetworkSerializer = System.Dictionary(System.Type, VoidSharpNetworking.INetworkSerializer)
end)
System.namespace("VoidSharp.Networking", function (namespace)
  namespace.class("SerializerMap", function (namespace)
    local RegisterSerializer, class, static
    static = function (this)
      this.Serializers = DictTypeINetworkSerializer()
    end
    RegisterSerializer = function (TType, TSerializer)
      local t = TSerializer()
      class.Serializers:set(System.typeof(TType), t)
    end
    class = {
      RegisterSerializer = RegisterSerializer,
      static = static,
      __metadata__ = function (out)
        return {
          properties = {
            { "Serializers", 0xE, System.Dictionary(System.Type, out.VoidSharp.Networking.INetworkSerializer) }
          },
          methods = {
            { "RegisterSerializer", 0x2000E, RegisterSerializer, function (TType, TSerializer) return end }
          },
          class = { 0xE }
        }
      end
    }
    return class
  end)
end)
