-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.Networking.Serializers", function (namespace)
  namespace.class("BoolSerializer", function (namespace)
    local Write, Read
    Write = function (this, writer, val)
      net.WriteBool(System.cast(System.Boolean, val))
    end
    Read = function (this, reader)
      return net.ReadBool()
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Networking.INetworkSerializer
        }
      end,
      Write = Write,
      Read = Read,
      __metadata__ = function (out)
        return {
          methods = {
            { "Read", 0x186, Read, out.VoidSharp.Networking.NetworkReader, System.Object },
            { "Write", 0x206, Write, out.VoidSharp.Networking.NetworkWriter, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
