-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.Networking.Serializers", function (namespace)
  namespace.class("ColorSerializer", function (namespace)
    local Write, Read
    Write = function (this, writer, val)
      writer:WriteColor(System.cast(VoidSharp.Color, val))
    end
    Read = function (this, reader)
      return reader:ReadColor()
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Networking.INetworkSerializer
        }
      end,
      Write = Write,
      Read = Read,
      __metadata__ = function (out)
        return {
          methods = {
            { "Read", 0x186, Read, out.VoidSharp.Networking.NetworkReader, System.Object },
            { "Write", 0x206, Write, out.VoidSharp.Networking.NetworkWriter, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
