-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.Networking.Serializers", function (namespace)
  namespace.class("DateTimeSerializer", function (namespace)
    local Write, Read
    Write = function (this, writer, val)
      local time = System.cast(System.DateTime, val)
      local totalSeconds = System.ToInt32(time:Subtract(System.DateTime(1970, 1, 1)):getTotalSeconds())
      net.WriteUInt(totalSeconds, 32)
    end
    Read = function (this, reader)
      local timestamp = System.cast(System.Int32, net.ReadUInt(32))
      return System.DateTime(1970, 1, 1):AddSeconds(timestamp)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Networking.INetworkSerializer
        }
      end,
      Write = Write,
      Read = Read,
      __metadata__ = function (out)
        return {
          methods = {
            { "Read", 0x186, Read, out.VoidSharp.Networking.NetworkReader, System.Object },
            { "Write", 0x206, Write, out.VoidSharp.Networking.NetworkWriter, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
