-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.ORM.Serializers", function (namespace)
  namespace.class("ColorSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, driver)
      local color = System.cast(VoidSharp.Color, obj)
      return "'" .. color.R .. "," .. color.G .. "," .. color.B .. "," .. color.A .. "'"
    end
    Deserialize = function (this, obj)
      local str = obj:ToString()
      local strs = Linq.ToList(str:Split(",", 0))
      local ints = Linq.ToList(Linq.Select(strs, System.Int32.Parse, System.Int32))

      return VoidSharp.Color(ints:get(0), ints:get(1), ints:get(2), ints:get(3))
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
