-- Generated by CSharp.lua Compiler
local System = System
local SystemGlobalization = System.Globalization
local VoidSharpORM
System.import(function (out)
  VoidSharpORM = VoidSharp.ORM
end)
System.namespace("VoidSharp.ORM.Serializers", function (namespace)
  namespace.class("DateTimeSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, driver)
      local time = System.cast(System.DateTime, obj)
      return time:Subtract(System.DateTime(1970, 1, 1)):getTotalSeconds():ToString(SystemGlobalization.CultureInfo.getInvariantCulture())
    end
    Deserialize = function (this, obj)
      local timestamp = VoidSharpORM.SerializerMap.ConvertToInt(obj)
      return System.DateTime(1970, 1, 1):AddSeconds(timestamp)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
