-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.ORM.Serializers", function (namespace)
  namespace.class("DynamicSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, databaseDriver)
      local str = VoidSharp.JSON.Serialize(obj, false)
      local escaped = databaseDriver:Escape(str, true)
      return escaped
    end
    Deserialize = function (this, obj)
      return VoidSharp.JSON.Parse(System.cast(System.String, obj))
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
