-- Generated by CSharp.lua Compiler
local System = System
local VoidSharpDarkRP
System.import(function (out)
  VoidSharpDarkRP = VoidSharp.DarkRP
end)
System.namespace("VoidSharp.ORM.Serializers", function (namespace)
  namespace.class("JobSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, databaseDriver)
      local job = System.cast(VoidSharpDarkRP.Job, obj)
      return "'" .. job.Command .. "'"
    end
    Deserialize = function (this, obj)
      return VoidSharpDarkRP.DarkRP.GetJobByCommand(System.cast(System.String, obj))
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
