-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.ORM.Serializers", function (namespace)
  namespace.class("StringSerializer", function (namespace)
    local Serialize, Deserialize
    Serialize = function (this, obj, driver)
      local str = driver:Escape(System.cast(System.String, obj), true)

      return "'" .. str .. "'"
    end
    Deserialize = function (this, obj)
      return obj
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.ORM.ISerializerBase
        }
      end,
      Serialize = Serialize,
      Deserialize = Deserialize,
      __metadata__ = function (out)
        return {
          methods = {
            { "Deserialize", 0x186, Deserialize, System.Object, System.Object },
            { "Serialize", 0x286, Serialize, System.Object, out.VoidSharp.IDatabaseDriver, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
