-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.Derma", function (namespace)
  namespace.class("Button", function (namespace)
    local DoClick, getFont, setFont, getText, setText, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "DButton")
    end
    DoClick = function (this, callback)
      this.VGUIPanel.DoClick = callback
    end
    getFont = function (this)
      return this.VGUIPanel:GetFont()
    end
    setFont = function (this, value)
      this.VGUIPanel:SetFont(value)
    end
    getText = function (this)
      return this.VGUIPanel:GetText()
    end
    setText = function (this, value)
      this.VGUIPanel:SetText(value)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      DoClick = DoClick,
      getFont = getFont,
      setFont = setFont,
      getText = getText,
      setText = setText,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "DoClick", 0x106, DoClick, System.Delegate }
          },
          properties = {
            { "Font", 0x106, System.String, getFont, setFont },
            { "Text", 0x106, System.String, getText, setText }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
