-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.Derma", function (namespace)
  namespace.class("TextEntry", function (namespace)
    local getValue, setValue, getNumeric, setNumeric, getUpdateOnType, setUpdateOnType, OnValueChange, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "DTextEntry")
    end
    getValue = function (this)
      return this.VGUIPanel:GetValue()
    end
    setValue = function (this, value)
      this.VGUIPanel:SetValue(value)
    end
    getNumeric = function (this)
      return this.VGUIPanel:GetNumeric()
    end
    setNumeric = function (this, value)
      this.VGUIPanel:SetNumeric(value)
    end
    getUpdateOnType = function (this)
      return this.VGUIPanel:GetUpdateOnType()
    end
    setUpdateOnType = function (this, value)
      this.VGUIPanel:SetUpdateOnType(value)
    end
    OnValueChange = function (this, callback)
      this.VGUIPanel.OnValueChange = callback
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      getValue = getValue,
      setValue = setValue,
      getNumeric = getNumeric,
      setNumeric = setNumeric,
      getUpdateOnType = getUpdateOnType,
      setUpdateOnType = setUpdateOnType,
      OnValueChange = OnValueChange,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "OnValueChange", 0x106, OnValueChange, System.Delegate(System.Object, System.String, System.Void) }
          },
          properties = {
            { "Numeric", 0x106, System.Boolean, getNumeric, setNumeric },
            { "UpdateOnType", 0x106, System.Boolean, getUpdateOnType, setUpdateOnType },
            { "Value", 0x106, System.String, getValue, setValue }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
