-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp", function (namespace)
  namespace.class("Color", function (namespace)
    local ToString, FromGmodColor, ToGmodColor, White, Black, Red, Green, Blue, 
    class, static, __ctor__
    static = function (this)
      White = class(255, 255, 255, 255)
      this.White = White
      Black = class(0, 0, 0, 255)
      this.Black = Black
      Red = class(255, 0, 0, 255)
      this.Red = Red
      Green = class(0, 255, 0, 255)
      this.Green = Green
      Blue = class(0, 0, 255, 255)
      this.Blue = Blue
    end
    __ctor__ = function (this, r, g, b, a)
      this.R = r
      this.G = g
      this.B = b
      this.A = a
    end
    ToString = function (this)
      return "Color(" .. this.R .. ", " .. this.G .. ", " .. this.B .. ", " .. this.A .. ")"
    end
    -- <summary>
    -- Converts the lua color to a C# Color Object
    -- </summary>
    -- <param name="col"></param>
    -- <returns></returns>
    FromGmodColor = function (col)
      return class(col.r, col.g, col.b, col.a)
    end
    -- <summary>
    -- Converts the C# Color object to a lua color
    -- </summary>
    -- <returns></returns>
    ToGmodColor = function (this)
      local obj = nil
      obj = Color(this.R, this.G, this.B, this.A)
      return obj
    end
    class = {
      R = 0,
      G = 0,
      B = 0,
      A = 0,
      ToString = ToString,
      FromGmodColor = FromGmodColor,
      ToGmodColor = ToGmodColor,
      static = static,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "A", 0x6, System.Int32 },
            { "B", 0x6, System.Int32 },
            { "G", 0x6, System.Int32 },
            { "R", 0x6, System.Int32 }
          },
          methods = {
            { ".ctor", 0x406, nil, System.Int32, System.Int32, System.Int32, System.Int32 },
            { "FromGmodColor", 0x18E, FromGmodColor, System.Object, class },
            { "ToGmodColor", 0x86, ToGmodColor, System.Object },
            { "ToString", 0x86, ToString, System.String }
          },
          fields = {
            { "Black", 0xE, class },
            { "Blue", 0xE, class },
            { "Green", 0xE, class },
            { "Red", 0xE, class },
            { "White", 0xE, class }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
