-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp", function (namespace)
  namespace.class("Entity", function (namespace)
    local getIsPlayer, getIsValid, getClass, getModel, setModel, getPos, setPos, getColor, 
    setColor, FromGmod, class, __ctor1__, __ctor2__, __ctor3__
    __ctor1__ = function (this, entity)
      this.GmodEntity = entity
    end
    __ctor2__ = function (this, entity, sig)
      this.GmodEntity = entity
    end
    __ctor3__ = function (this, className)
      this.GmodEntity = VoidSharp.Globals.getEnts():Create(className)
    end
    getIsPlayer = function (this)
      return this.GmodEntity:IsPlayer()
    end
    getIsValid = function (this)
      return this.GmodEntity:IsValid()
    end
    getClass = function (this)
      return this.GmodEntity:GetClass()
    end
    getModel = function (this)
      return this.GmodEntity:GetModel()
    end
    setModel = function (this, value)
      this.GmodEntity:SetModel(value)
    end
    getPos = function (this)
      return this.GmodEntity:GetPos()
    end
    setPos = function (this, value)
      this.GmodEntity:SetPos(value)
    end
    getColor = function (this)
      return VoidSharp.Color.FromGmodColor(this.GmodEntity:GetColor())
    end
    setColor = function (this, value)
      this.GmodEntity:SetColor(value:ToGmodColor())
    end
    FromGmod = function (gmodEntity)
      return class(gmodEntity)
    end
    class = {
      getIsPlayer = getIsPlayer,
      getIsValid = getIsValid,
      getClass = getClass,
      getModel = getModel,
      setModel = setModel,
      getPos = getPos,
      setPos = setPos,
      getColor = getColor,
      setColor = setColor,
      FromGmod = FromGmod,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "Class", 0x206, System.String, getClass },
            { "Color", 0x106, out.VoidSharp.Color, getColor, setColor },
            { "GmodEntity", 0x6, System.Object },
            { "IsPlayer", 0x206, System.Boolean, getIsPlayer },
            { "IsValid", 0x206, System.Boolean, getIsValid },
            { "Model", 0x106, System.String, getModel, setModel },
            { "Pos", 0x106, out.Vector, getPos, setPos }
          },
          methods = {
            { ".ctor", 0x106, __ctor1__, System.Object },
            { ".ctor", 0x206, __ctor2__, System.Object, System.Boolean },
            { ".ctor", 0x106, __ctor3__, System.String },
            { "FromGmod", 0x18E, FromGmod, System.Object, class }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
