-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp", function (namespace)
  namespace.class("Game", function (namespace)
    local GetMap
    -- <summary>
    -- Returns the name of the current map, without a file extension. On the menu state, returns "menu".
    -- </summary>
    GetMap = function ()
      return VoidSharp.Globals.getGame():GetMap()
    end
    return {
      GetMap = GetMap,
      __metadata__ = function (out)
        return {
          methods = {
            { "GetMap", 0x8E, GetMap, System.String }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
