-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp", function (namespace)
  -- ReSharper disable once InconsistentNaming
  namespace.class("JSON", function (namespace)
    local Parse, Serialize, TableToDictionary, TableToList
    -- <summary>
    -- Converts JSON to a Table
    -- </summary>
    Parse = function (str)
      local func = VoidSharp.Globals.getUtil().JSONToTable
      return func(str)
    end
    -- <summary>
    -- Converts Table to JSON
    -- </summary>
    Serialize = function (obj, prettyPrint)
      local func = VoidSharp.Globals.getUtil().TableToJSON
      return func(obj, prettyPrint)
    end
    TableToDictionary = function (tbl, T)
      local dict = T()
      for key, value in pairs(tbl) do
          dict:Add(key, value)
      end
      return dict
    end
    TableToList = function (tbl, T)
      local list = T()
      for key, value in pairs(tbl) do
          tbl[key] = value
      end
      return list
    end
    return {
      Parse = Parse,
      Serialize = Serialize,
      TableToDictionary = TableToDictionary,
      TableToList = TableToList,
      __metadata__ = function (out)
        return {
          methods = {
            { "Parse", 0x18E, Parse, System.String, System.Object },
            { "Serialize", 0x28E, Serialize, System.Object, System.Boolean, System.String },
            { "TableToDictionary", 0x1018E, TableToDictionary, function (T) return System.Object, T end },
            { "TableToList", 0x1018E, TableToList, function (T) return System.Object, T end }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
