-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp", function (namespace)
  namespace.class("Player", function (namespace)
    local LocalPlayer, getNick, getSteamId, getSteamId64, getAlive, ChatPrint, class, __ctor__
    __ctor__ = function (this, gmodEntity)
      VoidSharp.Entity.__ctor__[1](this, gmodEntity)
    end
    LocalPlayer = function ()
      return class(_G:LocalPlayer())
    end
    getNick = function (this)
      return this.GmodEntity:Nick()
    end
    getSteamId = function (this)
      return this.GmodEntity:SteamID()
    end
    getSteamId64 = function (this)
      return this.GmodEntity:SteamID64()
    end
    getAlive = function (this)
      return this.GmodEntity:Alive()
    end
    -- <summary>
    -- Prints a message to the player's chat.
    -- </summary>
    -- <param name="message">The message to send.</param>
    ChatPrint = function (this, message)
      this.GmodEntity:ChatPrint(message)
    end
    class = {
      base = function (out)
        return {
          out.VoidSharp.Entity
        }
      end,
      LocalPlayer = LocalPlayer,
      getNick = getNick,
      getSteamId = getSteamId,
      getSteamId64 = getSteamId64,
      getAlive = getAlive,
      ChatPrint = ChatPrint,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x106, nil, System.Object },
            { "ChatPrint", 0x106, ChatPrint, System.String },
            { "LocalPlayer", 0x8E, LocalPlayer, class }
          },
          properties = {
            { "Alive", 0x206, System.Boolean, getAlive },
            { "Nick", 0x206, System.String, getNick },
            { "SteamId", 0x206, System.String, getSteamId },
            { "SteamId64", 0x206, System.String, getSteamId64 }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
