-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
local ListPlayer
System.import(function (out)
  VoidSharp = out.VoidSharp
  ListPlayer = System.List(VoidSharp.Player)
end)
System.namespace("VoidSharp", function (namespace)
  namespace.class("Players", function (namespace)
    local GetAll
    -- <summary>
    -- Gets all the current players in the server (not including connecting clients).
    -- </summary>
    GetAll = function ()
      local players = ListPlayer()
      for _, player in System.each(VoidSharp.Globals.getPlayers():GetAll()) do
        player = System.cast(System.Object, player)
        local ply = VoidSharp.Player(player)
        players:Add(ply)
      end
      return players:ToArray()
    end
    return {
      GetAll = GetAll,
      __metadata__ = function (out)
        return {
          methods = {
            { "GetAll", 0x8E, GetAll, System.Array(out.VoidSharp.Player) }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
