-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp", function (namespace)
  namespace.class("Realm", function (namespace)
    local IsServer, IsClient
    -- <summary>
    -- Returns if its a server
    -- </summary>
    IsServer = function ()
      return _G.SERVER
    end
    -- <summary>
    -- Returns if its a client
    -- </summary>
    IsClient = function ()
      return _G.CLIENT
    end
    return {
      IsServer = IsServer,
      IsClient = IsClient,
      __metadata__ = function (out)
        return {
          methods = {
            { "IsClient", 0x8E, IsClient, System.Boolean },
            { "IsServer", 0x8E, IsServer, System.Boolean }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
