-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp", function (namespace)


  -- ReSharper disable once InconsistentNaming

  -- ReSharper disable once InconsistentNaming
end)
