-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp", function (namespace)
  namespace.class("Surface", function (namespace)
    local SetDrawColor, DrawRect, SetFontColor, SetFont, SetTextPos, DrawText
    -- <summary>
    -- Set the color of any future shapes to be drawn.
    -- </summary>
    SetDrawColor = function (color)
      VoidSharp.Globals.getSurface():SetDrawColor(color:ToGmodColor())
    end
    -- <summary>
    -- Draws a solid rectangle on the screen.
    -- </summary>
    DrawRect = function (x, y, w, h)
      VoidSharp.Globals.getSurface():DrawRect(x, y, w, h)
    end
    -- <summary>
    -- Set the color of any future text to be drawn.
    -- </summary>
    SetFontColor = function (color)
      VoidSharp.Globals.getSurface():SetTextColor(color:ToGmodColor())
    end
    -- <summary>
    -- Set the current font to be used for text operations later.
    -- The fonts must first be created with surface.CreateFont or be one of the Default Fonts.
    -- </summary>
    SetFont = function (fontName)
      VoidSharp.Globals.getSurface():SetFont(fontName)
    end
    -- <summary>
    -- Set the top-left position to draw any future text at.
    -- </summary>
    SetTextPos = function (x, y)
      VoidSharp.Globals.getSurface():SetTextPos(x, y)
    end
    -- <summary>
    -- Draw the specified text on the screen, using the previously set position, font and color.
    -- </summary>
    DrawText = function (text)
      VoidSharp.Globals.getSurface():DrawText(text)
    end
    return {
      SetDrawColor = SetDrawColor,
      DrawRect = DrawRect,
      SetFontColor = SetFontColor,
      SetFont = SetFont,
      SetTextPos = SetTextPos,
      DrawText = DrawText,
      __metadata__ = function (out)
        return {
          methods = {
            { "DrawRect", 0x40E, DrawRect, System.Int32, System.Int32, System.Int32, System.Int32 },
            { "DrawText", 0x10E, DrawText, System.String },
            { "SetDrawColor", 0x10E, SetDrawColor, out.VoidSharp.Color },
            { "SetFont", 0x10E, SetFont, System.String },
            { "SetFontColor", 0x10E, SetFontColor, out.VoidSharp.Color },
            { "SetTextPos", 0x20E, SetTextPos, System.Int32, System.Int32 }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
