-- Generated by CSharp.lua Compiler
local System = System
local Linq = System.Linq.Enumerable
System.namespace("VoidSharp.Handlers", function (namespace)
  namespace.class("HookAttribute", function (namespace)
    local GetAllHookAttributes, class, __ctor__
    __ctor__ = function (this, hookName, hookId)
      System.Attribute.__ctor__(this)
      this.HookName = hookName
      this.HookId = hookId
    end
    -- <summary>
    -- Gets all methods which have a Hook attribute.
    -- </summary>
    -- <param name="type">The type (preferably Class) to check.</param>
    -- <returns>A list of MethodInfos.</returns>
    GetAllHookAttributes = function (type)
      local methods = Linq.ToList(Linq.Where(Linq.ToList(type:GetMethods()), function (x)
        return #x:GetCustomAttributes(System.typeof(class), false) > 0
      end))

      return methods
    end
    class = {
      base = function (out)
        return {
          System.Attribute
        }
      end,
      GetAllHookAttributes = GetAllHookAttributes,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "HookId", 0x6, System.String },
            { "HookName", 0x6, System.String }
          },
          methods = {
            { ".ctor", 0x206, nil, System.String, System.String },
            { "GetAllHookAttributes", 0x18E, GetAllHookAttributes, System.Type, System.List(System.Reflection.MethodInfo) }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
