-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("Frame", function (namespace)
    local SetTitle, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.Frame")
    end
    SetTitle = function (this, description)
      this.VGUIPanel:SetTitle(description)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      SetTitle = SetTitle,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "SetTitle", 0x106, SetTitle, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
