-- Generated by CSharp.lua Compiler
local System = System
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("Icons", function (namespace)
    local Material, Close, CloseX, Rename, Settings, Profile, RoundedBox, Faction, 
    Board, User, Add, EditCircle, Remove, Move, Deposit, Upgrades, 
    Lock, Rewards, Stats, Trophy, TrophyHollow, Search, static
    static = function (this)
      Material = _G.Material
      this.Material = Material
      Close = Material("voidui/close.png")
      this.Close = Close
      CloseX = Material("voidui/close-x.png")
      this.CloseX = CloseX
      Rename = Material("voidui/rename.png")
      this.Rename = Rename
      Settings = Material("voidui/settings.png")
      this.Settings = Settings
      Profile = Material("voidui/profile.png")
      this.Profile = Profile
      RoundedBox = Material("voidui/roundedbox.png", "alphatest smooth")
      this.RoundedBox = RoundedBox
      Faction = Material("voidui/faction.png")
      this.Faction = Faction
      Board = Material("voidui/board.png")
      this.Board = Board
      User = Material("voidui/user.png")
      this.User = User
      Add = Material("voidui/add.png")
      this.Add = Add
      EditCircle = Material("voidui/edit-circle.png")
      this.EditCircle = EditCircle
      Remove = Material("voidui/remove.png")
      this.Remove = Remove
      Move = Material("voidui/move.png")
      this.Move = Move
      Deposit = Material("voidui/deposit.png")
      this.Deposit = Deposit
      Upgrades = Material("voidui/upgrades.png")
      this.Upgrades = Upgrades
      Lock = Material("voidui/lock.png")
      this.Lock = Lock
      Rewards = Material("voidui/rewards.png")
      this.Rewards = Rewards
      Stats = Material("voidui/stats.png")
      this.Stats = Stats
      Trophy = Material("voidui/trophy.png")
      this.Trophy = Trophy
      TrophyHollow = Material("voidui/trophy_hollow.png")
      this.TrophyHollow = TrophyHollow
      Search = Material("voidui/search.png")
      this.Search = Search
    end
    return {
      static = static,
      __metadata__ = function (out)
        return {
          fields = {
            { "Add", 0xE, System.Object },
            { "Board", 0xE, System.Object },
            { "Close", 0xE, System.Object },
            { "CloseX", 0xE, System.Object },
            { "Deposit", 0xE, System.Object },
            { "EditCircle", 0xE, System.Object },
            { "Faction", 0xE, System.Object },
            { "Lock", 0xE, System.Object },
            { "Material", 0xE, System.Object },
            { "Move", 0xE, System.Object },
            { "Profile", 0xE, System.Object },
            { "Remove", 0xE, System.Object },
            { "Rename", 0xE, System.Object },
            { "Rewards", 0xE, System.Object },
            { "RoundedBox", 0xE, System.Object },
            { "Search", 0xE, System.Object },
            { "Settings", 0xE, System.Object },
            { "Stats", 0xE, System.Object },
            { "Trophy", 0xE, System.Object },
            { "TrophyHollow", 0xE, System.Object },
            { "Upgrades", 0xE, System.Object },
            { "User", 0xE, System.Object }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
