-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("Sidebar", function (namespace)
    local SetAccentColor, SetFadeSpeed, SetActive, SelectTab, SwitchTab, AddTab, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.Sidebar")
    end
    SetAccentColor = function (this, color)
      this.VGUIPanel:SetAccentColor(color:ToGmodColor())
    end
    SetFadeSpeed = function (this, speed)
      this.VGUIPanel:SetFadeSpeed(speed)
    end
    SetActive = function (this, active)
      this.VGUIPanel:SetActive(active)
    end
    SelectTab = function (this, tab)
      this.VGUIPanel:SelectTab(tab.VGUIPanel)
    end
    SwitchTab = function (this, tab, panel)
      this.VGUIPanel:SwitchTab(tab.VGUIPanel, panel.VGUIPanel)
    end
    AddTab = function (this, text, icon, panel, bottomAlign, iconSize)
      this.VGUIPanel:AddTab(text, icon, panel.VGUIPanel, bottomAlign, iconSize)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      SetAccentColor = SetAccentColor,
      SetFadeSpeed = SetFadeSpeed,
      SetActive = SetActive,
      SelectTab = SelectTab,
      SwitchTab = SwitchTab,
      AddTab = AddTab,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "AddTab", 0x506, AddTab, System.String, System.String, out.VoidSharp.Panel, System.Boolean, System.Array(System.Int32) },
            { "SelectTab", 0x106, SelectTab, out.VoidSharp.Panel },
            { "SetAccentColor", 0x106, SetAccentColor, out.VoidSharp.Color },
            { "SetActive", 0x106, SetActive, System.Boolean },
            { "SetFadeSpeed", 0x106, SetFadeSpeed, System.Single },
            { "SwitchTab", 0x206, SwitchTab, out.VoidSharp.Panel, out.VoidSharp.Panel }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
