-- Generated by CSharp.lua Compiler
local System = System
local ListString = System.List(System.String)
local VoidSharpDarkRP
System.import(function (out)
  VoidSharpDarkRP = VoidSharp.DarkRP
end)
System.namespace("VoidSharp.DarkRP", function (namespace)
  namespace.class("Job", function (namespace)
    local __ctor__
    __ctor__ = function (this, team)
      local jobTable = VoidSharpDarkRP.DarkRP.GetJob(team)
      if jobTable == nil then
        System.throw(System.Exception("The specified job does not exist."))
      end

      this.Category = jobTable.category
      this.Command = jobTable.command
      this.Description = jobTable.description
      this.Salary = jobTable.salary
      this.MaxPlayers = jobTable.max

      local models = ListString()

      if (istable(jobTable.model)) then
          for k, v in ipairs(jobTable.model) do
              models:Add(v)
          end
      else
          models:Add(jobTable.model)
      end

      this.Models = models:ToArray()

      this.Team = team
    end
    return {
      Salary = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Category", 0x6, System.String },
            { "Command", 0x6, System.String },
            { "Description", 0x6, System.String },
            { "MaxPlayers", 0x6, System.Nullable(System.Int32) },
            { "Models", 0x6, System.Array(System.String) },
            { "Salary", 0x6, System.Int32 },
            { "Team", 0x6, out.VoidSharp.Team }
          },
          methods = {
            { ".ctor", 0x106, nil, out.VoidSharp.Team }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
