-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("BackgroundPanel", function (namespace)
    local SetTitle, SetFont, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.BackgroundPanel")
    end
    SetTitle = function (this, title)
      this.VGUIPanel:SetTitle(title)
    end
    SetFont = function (this, font)
      this.VGUIPanel:SetFont(font)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      SetTitle = SetTitle,
      SetFont = SetFont,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "SetFont", 0x106, SetFont, System.String },
            { "SetTitle", 0x106, SetTitle, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
