-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("Button", function (namespace)
    local SetColor, SetColor1, SetMedium, SetSmaller, SetCompact, SetTextColor, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.Button")
    end
    SetColor = function (this, color)
      this.VGUIPanel:SetColor(color:ToGmodColor())
    end
    SetColor1 = function (this, color, bgColor)
      this.VGUIPanel:SetColor(color:ToGmodColor(), bgColor:ToGmodColor())
    end
    SetMedium = function (this)
      this.VGUIPanel:SetMedium()
    end
    SetSmaller = function (this)
      this.VGUIPanel:SetSmaller()
    end
    SetCompact = function (this)
      this.VGUIPanel:SetCompact()
    end
    SetTextColor = function (this, color)
      this.VGUIPanel:SetTextColor(color:ToGmodColor())
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      SetColor = SetColor,
      SetColor1 = SetColor1,
      SetMedium = SetMedium,
      SetSmaller = SetSmaller,
      SetCompact = SetCompact,
      SetTextColor = SetTextColor,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "SetColor", 0x106, SetColor, out.VoidSharp.Color },
            { "SetColor", 0x206, SetColor1, out.VoidSharp.Color, out.VoidSharp.Color },
            { "SetCompact", 0x6, SetCompact },
            { "SetMedium", 0x6, SetMedium },
            { "SetSmaller", 0x6, SetSmaller },
            { "SetTextColor", 0x106, SetTextColor, out.VoidSharp.Color }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
