-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("ColorPicker", function (namespace)
    local getColor, setColor, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.ColorMixer")
    end
    getColor = function (this)
      return VoidSharp.Color.FromGmodColor(this.VGUIPanel.colorMixer:GetColor())
    end
    setColor = function (this, value)
      this.VGUIPanel.colorMixer:SetColor(value:ToGmodColor())
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      getColor = getColor,
      setColor = setColor,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil }
          },
          properties = {
            { "Color", 0x106, out.VoidSharp.Color, getColor, setColor }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
