-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("Dropdown", function (namespace)
    local ChooseOption, SetLight, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.Dropdown")
    end
    ChooseOption = function (this, value, index)
      this.VGUIPanel:ChooseOption(value, index)
    end
    SetLight = function (this)
      this.VGUIPanel:SetLight()
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      ChooseOption = ChooseOption,
      SetLight = SetLight,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "ChooseOption", 0x206, ChooseOption, System.String, System.Int32 },
            { "SetLight", 0x6, SetLight }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
