-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("ElementGrid", function (namespace)
    local AddElement, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.ElementGrid")
    end
    AddElement = function (this, title, element, height, noCell)
      this.VGUIPanel:AddElement(title, element, height, noCell)
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      AddElement = AddElement,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "AddElement", 0x406, AddElement, System.String, System.String, System.Int32, System.Boolean }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
