-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("Search", function (namespace)
    local OnSearch, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.Search")
    end
    OnSearch = function (this, action)
      this.VGUIPanel.self.OnSearch = action
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      OnSearch = OnSearch,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "OnSearch", 0x106, OnSearch, System.Delegate(System.String, System.Void) }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
