-- Generated by CSharp.lua Compiler
local System = System
local VoidSharp
System.import(function (out)
  VoidSharp = out.VoidSharp
end)
System.namespace("VoidSharp.VoidUI", function (namespace)
  namespace.class("TextInput", function (namespace)
    local getValue, setValue, SetFont, SetNumeric, OnValueChange, __ctor__
    __ctor__ = function (this)
      VoidSharp.Panel.__ctor__[1](this, "VoidUI.TextInput")
    end
    getValue = function (this)
      return this.VGUIPanel.entry:GetValue()
    end
    setValue = function (this, value)
      this.VGUIPanel.entry:SetColor(value)
    end
    SetFont = function (this, font)
      this.VGUIPanel:SetFont(font)
    end
    SetNumeric = function (this, b)
      this.VGUIPanel:SetNumeric(b)
    end
    OnValueChange = function (this, action)
      this.VGUIPanel.OnValueChange = action
    end
    return {
      base = function (out)
        return {
          out.VoidSharp.Panel
        }
      end,
      getValue = getValue,
      setValue = setValue,
      SetFont = SetFont,
      SetNumeric = SetNumeric,
      OnValueChange = OnValueChange,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "OnValueChange", 0x106, OnValueChange, System.Delegate(System.String, System.Void) },
            { "SetFont", 0x106, SetFont, System.String },
            { "SetNumeric", 0x106, SetNumeric, System.Boolean }
          },
          properties = {
            { "Value", 0x106, System.Object, getValue, setValue }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
